app/serializers/concerns/case_mixin.rb
plugin.rb

Visiting the `/c` route when the plugin is enabled results in 
```
HasCustomFields::NotPreloadedError in CategoriesController#index
```
Preloading the `has_salesforce_case` custom field fixes the issue.

FIX: preload topic custom fields

---

plugin.rb

This was breaking the frontend when visiting /admin/plugins

FIX: remove unused admin route

---

app/controllers/salesforce/persons_controller.rb
app/jobs/scheduled/sync_salesforce_users.rb
app/models/salesforce/contact.rb
app/models/salesforce/lead.rb
app/models/salesforce/person.rb
db/fixtures/001_groups.rb
lib/salesforce/api.rb
plugin.rb
spec/jobs/create_feed_item_spec.rb
spec/jobs/sync_salesforce_users_spec.rb
spec/models/feed_item_spec.rb
spec/requests/persons_controller_spec.rb

When a new user join on Discourse it will check Salesforce for any existing lead/contact object. Then it will update the object id in user custom field if available.
Also did some code refactoring.

FEATURE: sync Salesforce lead/contact on user account creation.

---

app/controllers/salesforce/admin_controller.rb
config/locales/server.en.yml
config/settings.yml
lib/salesforce/api.rb
plugin.rb

Salesforce has sandbox mode where they will use different authorization server URL. Previosuly, we didn't had an option to change it.

FEATURE: add new site setting to change authorization server's url.

---

plugin.rb

Related core PR: https://github.com/discourse/discourse/pull/19127.
Internal topic: t/82084.

DEV: Explicitly define primary_email_verified? method for Salesforce authenticator

---

db/fixtures/001_groups.rb
plugin.rb
spec/requests/cases_controller_spec.rb
spec/requests/persons_controller_spec.rb

Co-authored-by: Ted Johansson <drenmi@gmail.com>
The seed groups in this plugin break some expectations in the core test suite about what groups are in the DB.
This change makes it so we don't seed the groups in the test environment.
We briefly considered three approaches:
Do not add the seeds in test environment. (This change.) Make core group tests less strict.
Allow plugins to add to `AUTO_GROUPS`.
The last one is promising, but potentially requires a lot of work. We're going with the first one for now since it's quick and easy.
Mostly copied from the PR https://github.com/discourse/discourse-salesforce/pull/37

DEV: Do not seed groups in test environment

---

plugin.rb

Since, both `title` and `flair_icon` are viewable by everyone don't set it while seeding the groups by default. Admins can add it later if they want.

DEV: do not set `title` and `flair_icon` for seeded groups.

---

app/models/salesforce/case.rb
config/settings.yml

Previously, we used a hardcoded value "Web" by default. Now you can change it in the site setting.

FEATURE: add a new site setting to set case origin.

---

config/locales/server.en.yml

UX: Drop unneeded comma in a string

---

app/models/salesforce/case.rb
config/locales/server.en.yml
config/settings.yml
spec/models/case_spec.rb

Currently, a new Salesforce contact is created during Case sync if the topic creator isn't mapped to a Salesforce contact during case sync.
This change introduces a site setting to conditionally create and map contact during case sync.

FEATURE: Optionally skip contact creation on case sync

---

app/models/salesforce/case.rb
config/locales/server.en.yml
config/settings.yml
spec/models/case_spec.rb

Currently, enabling `salesforce_skip_contact_creation_on_case_sync` Site Setting allows cases to be created/synce without contacts.
This change introduces `salesforce_default_contact_id_for_case_sync` Site Setting for configuring a given Salesforce Contact as default Contact for use during case sync when `salesforce_skip_contact_creation_on_case_sync`  is enabeld.

FEATURE: Add default Contact ID for Case Sync Site Setting

---

app/models/salesforce/case.rb
spec/models/case_spec.rb

There is currently no way to sync custom fields for any of the Salesforce objects in this plugin.
This change allows for the Case request payload to be extended by other plugins to permit syncing of customer specific custom fields.

DEV: Allow Case payload modification via a plugin modifiers

---

app/jobs/scheduled/sync_salesforce_users.rb
spec/jobs/sync_salesforce_users_spec.rb

Right now when the credentials are wrong, getting the access token during the sync job fails the job.
This prevents the job from failing. 
This credential error is currently properly shown to the user when the user is trying to create a new lead.

DEV: Prevent sync jobs from failing if API keys are wrong

---

lib/salesforce/api.rb
plugin.rb
spec/lib/api_spec.rb
spec/spec_helper.rb

On `user_created` event we should check whether we have API credentials or not before performing the sync with Salesforce.

FIX: don't sync new user if API credentials are not available.

---

config/locales/client.en.yml
config/settings.yml

This is so the plugins settings are better categorized in the site settings UI.

DEV: Change settings root from plugins: to discourse_salesforce

---

.discourse-compatibility
assets/javascripts/discourse/initializers/extend-for-salesforce.js

It's been broken since float kit has been introduced, this should now correctly show the buttons in the post admin menu.

FIX: uses new addPostAdminMenuButton api

---

app/jobs/regular/sync_salesforce_user.rb
plugin.rb
spec/models/user_spec.rb

Otherwise, it will show an error in the signup form even after the user is created when the API call fails. This commit adds a new job `SyncSalesforceUser` that is responsible for syncing Salesforce user information. The job checks if Salesforce integration is enabled and then retrieves the user's Salesforce contact or lead ID based on their email. If a match is found, the user's custom fields are saved.

FIX: move Salesforce API calls to background job.

---

app/controllers/salesforce/admin_controller.rb
spec/requests/admin_controller_spec.rb

When redirecting to an external URL with Rails 7+, the `allow_other_host` option is needed.

FIX: Add Rails 7+ compatibility

---

app/jobs/scheduled/sync_salesforce_users.rb
spec/jobs/sync_salesforce_users_spec.rb

We have an existing site setting for logging API errors. Using it to log an error syncing users.

DEV: Log credentials error from SyncSalesforceUsers job 

---

app/jobs/scheduled/sync_salesforce_users.rb
spec/jobs/sync_salesforce_users_spec.rb

This reverts commit 5f67c9f7b2e825a115f4174f8ff8fc8ed45cd4df.
It wasn't necessary. This added a double-log. I had thought we weren't logging an error, when we actually were :) 
Proof:

REVERT: "DEV: Log credentials error from SyncSalesforceUsers job  (#111)"

---

app/services/salesforce/problem_check/salesforce_app_not_approved.rb
config/locales/server.en.yml
lib/salesforce/api.rb
plugin.rb
spec/lib/api_spec.rb
spec/spec_helper.rb

`AdminDashboardData#add_problem_message` used to allow setting an arbitrary admin notice in the old problem check system. With the introduction of the new system, this is handled by inline problem checks.
This PR replaces the former with the latter.

DEV: Replace deprecated add_problem_message with inline problem check
